### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ghost** [MattVsTheWorld/AGP_GroupProject#1]
Hello. Project errors with missed dependencies (GLEW, glm, etc.).

**Comment by MattVsTheWorld** [comment]
Hi!
Yes, dependencies are set to look for said libraries in a specific folder (C:/dev in this case), which is of course not ideal.

However, this is an old university project and wasn't designed for use outside of that context.

The repository is used merely as exposition of past work done.

**Comment by ghost** [comment]
I just wanted to make new POM with hierarchy (alike HBZ technique).
